#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"
export PYTHONPATH="$ROOT/src:${PYTHONPATH:-}"
export OMNIVOICE_MODEL_ID="${OMNIVOICE_MODEL_ID:-k2-fsa/OmniVoice}"
export OMNIVOICE_PORT="${OMNIVOICE_PORT:-9194}"
export OMNIVOICE_GPU_INFERER="${OMNIVOICE_GPU_INFERER:-1}"
export OMNIVOICE_BATCH_SIZE="${OMNIVOICE_BATCH_SIZE:-16}"
export OMNIVOICE_BATCH_WAIT_MS="${OMNIVOICE_BATCH_WAIT_MS:-250}"
export OMNIVOICE_CUDA_STREAMS="${OMNIVOICE_CUDA_STREAMS:-2}"
export OMNIVOICE_CUDA_GRAPH_MIN_WIDTH="${OMNIVOICE_CUDA_GRAPH_MIN_WIDTH:-32}"
export OMNIVOICE_RUNNER_MODE="${OMNIVOICE_RUNNER_MODE:-hybrid}"
PYTHON_BIN="${OMNIVOICE_PYTHON:-python}"

cd "$ROOT"
exec "$PYTHON_BIN" -m launcher "$@"
